[build]
  command = "npm run generate"
  publish = ".output/public"

[build.environment]
  NUXT_PUBLIC_SUPABASE_URL = ""
  NUXT_PUBLIC_SUPABASE_ANON_KEY = ""
  OPENROUTER_API_KEY = ""
  GEMINI_API_KEY = ""
  GEMINI_MODEL = "" 