[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NUXT_PUBLIC_SUPABASE_URL = ""
  NUXT_PUBLIC_SUPABASE_ANON_KEY = ""
  GEMINI_API_KEY = ""
  GEMINI_MODEL = "gemini-2.0-flash"

# Handle client-side routing (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirects for your pages
[[redirects]]
  from = "/analysis"
  to = "/analysis/index.html"
  status = 200

[[redirects]]
  from = "/analysis-report"
  to = "/analysis-report/index.html"
  status = 200

[[redirects]]
  from = "/credit-analysis"
  to = "/credit-analysis/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache" 