<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
    <!-- Header -->
    <div class="bg-white shadow-lg border-b">
      <div class="max-w-7xl mx-auto px-6 py-6">
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-4">
            <div class="text-3xl">📊</div>
            <div>
              <h1 class="text-3xl font-bold text-gray-900">Investment Analysis Report</h1>
              <p class="text-gray-600">Generated by danakito AI • {{ new Date().toLocaleDateString() }}</p>
            </div>
          </div>
          <div class="flex space-x-3">
            <button
              @click="downloadReport"
              class="bg-green-600 hover:bg-green-700 text-white px-6 py-2 rounded-lg transition-colors flex items-center space-x-2"
            >
              <span>📥</span>
              <span>Download PDF</span>
            </button>
            <button
              @click="window.print()"
              class="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg transition-colors flex items-center space-x-2"
            >
              <span>🖨️</span>
              <span>Print</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="max-w-7xl mx-auto px-6 py-8 space-y-8">
      <!-- Loading State -->
      <div v-if="loading" class="text-center py-20">
        <div class="animate-spin rounded-full h-16 w-16 border-b-4 border-blue-600 mx-auto mb-4"></div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">🧠 Generating AI Analysis Report...</h3>
        <p class="text-gray-600">Processing market data and generating insights...</p>
      </div>

      <!-- Report Content -->
      <div v-else-if="reportData" class="space-y-8">
        <!-- Executive Summary -->
        <div class="bg-white rounded-xl shadow-lg p-8">
          <h2 class="text-2xl font-bold text-gray-900 mb-6 flex items-center">
            <span class="mr-3">📋</span>
            Executive Summary
          </h2>
          
          <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div class="bg-gradient-to-r from-green-50 to-green-100 rounded-lg p-6 text-center">
              <div class="text-3xl font-bold text-green-600">{{ reportData.score }}%</div>
              <div class="text-sm text-green-700 font-medium">Investment Score</div>
            </div>
            <div class="bg-gradient-to-r from-blue-50 to-blue-100 rounded-lg p-6 text-center">
              <div class="text-2xl font-bold text-blue-600">{{ reportData.roi }}</div>
              <div class="text-sm text-blue-700 font-medium">Projected ROI</div>
            </div>
            <div class="bg-gradient-to-r from-orange-50 to-orange-100 rounded-lg p-6 text-center">
              <div class="text-2xl font-bold text-orange-600">{{ reportData.risk }}</div>
              <div class="text-sm text-orange-700 font-medium">Risk Level</div>
            </div>
          </div>

          <div class="prose max-w-none">
            <p class="text-gray-700 leading-relaxed">{{ reportData.recommendation }}</p>
          </div>
        </div>

        <!-- Investment vs Loan Comparison Chart -->
        <div class="bg-white rounded-xl shadow-lg p-8">
          <h3 class="text-xl font-bold text-gray-900 mb-6 flex items-center">
            <span class="mr-3">💰</span>
            Investment vs Loan Analysis
          </h3>
          
          <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <!-- Investment Growth Chart -->
            <div>
              <h4 class="text-lg font-semibold text-gray-800 mb-4">Investment Growth Projection (5 Years)</h4>
              <div class="space-y-3">
                <div v-for="(year, index) in projectionData.investmentGrowth" :key="index" class="flex items-center">
                  <div class="w-16 text-sm font-medium text-gray-600">Year {{ index + 1 }}</div>
                  <div class="flex-1 mx-4">
                    <div class="w-full bg-gray-200 rounded-full h-4">
                      <div 
                        class="h-4 rounded-full bg-gradient-to-r from-green-400 to-green-600 transition-all duration-1000" 
                        :style="{ width: (year.value / projectionData.maxInvestment) * 100 + '%' }"
                      ></div>
                    </div>
                  </div>
                  <div class="w-24 text-right text-sm font-semibold text-green-600">
                    ${{ year.value.toLocaleString() }}
                  </div>
                </div>
              </div>
            </div>

            <!-- Loan Payment Chart -->
            <div>
              <h4 class="text-lg font-semibold text-gray-800 mb-4">Loan Payment Schedule (5 Years)</h4>
              <div class="space-y-3">
                <div v-for="(year, index) in projectionData.loanPayments" :key="index" class="flex items-center">
                  <div class="w-16 text-sm font-medium text-gray-600">Year {{ index + 1 }}</div>
                  <div class="flex-1 mx-4">
                    <div class="w-full bg-gray-200 rounded-full h-4">
                      <div 
                        class="h-4 rounded-full bg-gradient-to-r from-red-400 to-red-600 transition-all duration-1000" 
                        :style="{ width: (year.payment / projectionData.maxLoanPayment) * 100 + '%' }"
                      ></div>
                    </div>
                  </div>
                  <div class="w-24 text-right text-sm font-semibold text-red-600">
                    ${{ year.payment.toLocaleString() }}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Net Profit Chart -->
          <div class="mt-8">
            <h4 class="text-lg font-semibold text-gray-800 mb-4">Net Profit After Loan Payments</h4>
            <div class="space-y-3">
              <div v-for="(year, index) in projectionData.netProfit" :key="index" class="flex items-center">
                <div class="w-16 text-sm font-medium text-gray-600">Year {{ index + 1 }}</div>
                <div class="flex-1 mx-4">
                  <div class="w-full bg-gray-200 rounded-full h-6">
                    <div 
                      class="h-6 rounded-full transition-all duration-1000" 
                      :class="year.profit > 0 ? 'bg-gradient-to-r from-green-400 to-green-600' : 'bg-gradient-to-r from-red-400 to-red-600'"
                      :style="{ width: Math.abs(year.profit / projectionData.maxNetProfit) * 100 + '%' }"
                    ></div>
                  </div>
                </div>
                <div class="w-32 text-right text-sm font-semibold" :class="year.profit > 0 ? 'text-green-600' : 'text-red-600'">
                  {{ year.profit > 0 ? '+' : '' }}${{ year.profit.toLocaleString() }}
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Interest Rate Comparison -->
        <div class="bg-white rounded-xl shadow-lg p-8">
          <h3 class="text-xl font-bold text-gray-900 mb-6 flex items-center">
            <span class="mr-3">📈</span>
            Interest Rate Impact Analysis
          </h3>
          
          <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <!-- Different Interest Rates Comparison -->
            <div>
              <h4 class="text-lg font-semibold text-gray-800 mb-4">Total Cost at Different Interest Rates</h4>
              <div class="space-y-3">
                <div v-for="rate in interestRateComparison" :key="rate.rate" class="flex items-center">
                  <div class="w-16 text-sm font-medium text-gray-600">{{ rate.rate }}%</div>
                  <div class="flex-1 mx-4">
                    <div class="w-full bg-gray-200 rounded-full h-4">
                      <div 
                        class="h-4 rounded-full transition-all duration-1000" 
                        :class="rate.rate <= 7 ? 'bg-green-500' : rate.rate <= 8 ? 'bg-yellow-500' : 'bg-red-500'"
                        :style="{ width: (rate.totalCost / maxTotalCost) * 100 + '%' }"
                      ></div>
                    </div>
                  </div>
                  <div class="w-28 text-right text-sm font-semibold">
                    ${{ rate.totalCost.toLocaleString() }}
                  </div>
                </div>
              </div>
            </div>

            <!-- Monthly Payment Comparison -->
            <div>
              <h4 class="text-lg font-semibold text-gray-800 mb-4">Monthly Payment Comparison</h4>
              <div class="space-y-3">
                <div v-for="rate in interestRateComparison" :key="`monthly-${rate.rate}`" class="flex items-center">
                  <div class="w-16 text-sm font-medium text-gray-600">{{ rate.rate }}%</div>
                  <div class="flex-1 mx-4">
                    <div class="w-full bg-gray-200 rounded-full h-4">
                      <div 
                        class="h-4 rounded-full transition-all duration-1000" 
                        :class="rate.rate <= 7 ? 'bg-green-500' : rate.rate <= 8 ? 'bg-yellow-500' : 'bg-red-500'"
                        :style="{ width: (rate.monthlyPayment / maxMonthlyPayment) * 100 + '%' }"
                      ></div>
                    </div>
                  </div>
                  <div class="w-24 text-right text-sm font-semibold">
                    ${{ rate.monthlyPayment.toLocaleString() }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Break-even Analysis -->
        <div class="bg-white rounded-xl shadow-lg p-8">
          <h3 class="text-xl font-bold text-gray-900 mb-6 flex items-center">
            <span class="mr-3">⚖️</span>
            Break-even Analysis
          </h3>
          
          <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div class="bg-blue-50 rounded-lg p-6">
              <div class="text-center">
                <div class="text-3xl font-bold text-blue-600">{{ breakEvenData.months }}</div>
                <div class="text-sm text-blue-700 font-medium">Months to Break Even</div>
              </div>
            </div>
            <div class="bg-green-50 rounded-lg p-6">
              <div class="text-center">
                <div class="text-2xl font-bold text-green-600">${{ breakEvenData.monthlyRevenue.toLocaleString() }}</div>
                <div class="text-sm text-green-700 font-medium">Required Monthly Revenue</div>
              </div>
            </div>
            <div class="bg-purple-50 rounded-lg p-6">
              <div class="text-center">
                <div class="text-2xl font-bold text-purple-600">${{ breakEvenData.totalInvestment.toLocaleString() }}</div>
                <div class="text-sm text-purple-700 font-medium">Total Investment</div>
              </div>
            </div>
          </div>

          <!-- Break-even Timeline -->
          <div class="mt-8">
            <h4 class="text-lg font-semibold text-gray-800 mb-4">Break-even Timeline</h4>
            <div class="relative">
              <div class="w-full bg-gray-200 rounded-full h-6">
                <div 
                  class="bg-gradient-to-r from-red-400 via-yellow-400 to-green-500 h-6 rounded-full transition-all duration-2000" 
                  :style="{ width: Math.min((breakEvenData.months / 60) * 100, 100) + '%' }"
                ></div>
              </div>
              <div class="flex justify-between mt-2 text-xs text-gray-600">
                <span>Start</span>
                <span>{{ Math.floor(breakEvenData.months / 12) }} years {{ breakEvenData.months % 12 }} months</span>
                <span>5 Years</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Risk Assessment -->
        <div class="bg-white rounded-xl shadow-lg p-8">
          <h3 class="text-xl font-bold text-gray-900 mb-6 flex items-center">
            <span class="mr-3">⚠️</span>
            Risk Assessment & Mitigation
          </h3>
          
          <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div>
              <h4 class="text-lg font-semibold text-gray-800 mb-4">Risk Factors</h4>
              <div class="space-y-3">
                <div v-for="risk in reportData.riskFactors" :key="risk.factor" class="flex items-center">
                  <div 
                    class="w-3 h-3 rounded-full mr-3" 
                    :class="risk.level === 'High' ? 'bg-red-500' : risk.level === 'Medium' ? 'bg-yellow-500' : 'bg-green-500'"
                  ></div>
                  <div class="flex-1">
                    <div class="font-medium text-gray-900">{{ risk.factor }}</div>
                    <div class="text-sm text-gray-600">{{ risk.description }}</div>
                  </div>
                  <div 
                    class="px-2 py-1 rounded text-xs font-medium" 
                    :class="risk.level === 'High' ? 'bg-red-100 text-red-800' : risk.level === 'Medium' ? 'bg-yellow-100 text-yellow-800' : 'bg-green-100 text-green-800'"
                  >
                    {{ risk.level }}
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h4 class="text-lg font-semibold text-gray-800 mb-4">Mitigation Strategies</h4>
              <div class="space-y-3">
                <div v-for="strategy in reportData.mitigationStrategies" :key="strategy.title" class="border-l-4 border-blue-400 pl-4">
                  <div class="font-medium text-gray-900">{{ strategy.title }}</div>
                  <div class="text-sm text-gray-600">{{ strategy.description }}</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- AI Insights -->
        <div class="bg-gradient-to-r from-purple-50 to-pink-50 rounded-xl p-8">
          <h3 class="text-xl font-bold text-gray-900 mb-6 flex items-center">
            <span class="mr-3">🤖</span>
            AI-Generated Insights
          </h3>
          <div class="prose max-w-none">
            <div v-html="reportData.detailedAnalysis" class="text-gray-700 leading-relaxed"></div>
          </div>
        </div>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="text-center py-20">
        <div class="text-6xl mb-4">❌</div>
        <h3 class="text-xl font-semibold text-gray-900 mb-2">Analysis Failed</h3>
        <p class="text-gray-600 mb-4">{{ error }}</p>
        <button
          @click="generateReport"
          class="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg transition-colors"
        >
          Try Again
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useFetch } from '#imports'
// Load mock-data.json for overlays (for future map integration)
const { data: mockData, pending: loadingMockData } = await useFetch('/mock-data.json')

// SEO
useHead({
  title: 'Investment Analysis Report - danakito',
  meta: [
    { name: 'description', content: 'Detailed AI-powered investment analysis report with charts and projections' }
  ]
})

// Reactive state
const loading = ref(true)
const error = ref('')
const reportData = ref(null)
const projectionData = ref(null)
const interestRateComparison = ref([])
const breakEvenData = ref(null)

// Computed values for chart scaling
const maxTotalCost = computed(() => {
  if (!interestRateComparison.value.length) return 0
  return Math.max(...interestRateComparison.value.map(r => r.totalCost))
})

const maxMonthlyPayment = computed(() => {
  if (!interestRateComparison.value.length) return 0
  return Math.max(...interestRateComparison.value.map(r => r.monthlyPayment))
})

// Get parameters from URL
const route = useRoute()
const params = {
  creditAmount: Number(route.query.amount) || 250000,
  investmentType: route.query.type || 'retail',
  location: route.query.location || 'New York City, NY'
}

// Methods
const generateReport = async () => {
  loading.value = true
  error.value = ''
  
  try {
    console.log('Generating detailed analysis report...')
    
    // Call Gemini API for detailed analysis
const response = await $fetch('/api/analysis/gemini', {
      method: 'POST',
      body: {
        ...params,
        generateDetailedReport: true
      }
    })
    
    reportData.value = response
    
    // Generate projection data
    generateProjectionData()
    generateInterestRateComparison()
    generateBreakEvenData()
    
    console.log('Report generated successfully!', response)
  } catch (err) {
    console.error('Error generating report:', err)
    error.value = 'Failed to generate analysis report. Please try again.'
  } finally {
    loading.value = false
  }
}

const generateProjectionData = () => {
  const creditAmount = params.creditAmount
  const annualGrowthRate = 0.15 // 15% annual growth
  const loanRate = 0.075 // 7.5% annual interest
  const monthlyRate = loanRate / 12
  const termMonths = 60
  
  // Calculate monthly loan payment
  const monthlyPayment = creditAmount * (monthlyRate * Math.pow(1 + monthlyRate, termMonths)) / 
                        (Math.pow(1 + monthlyRate, termMonths) - 1)
  
  const investmentGrowth = []
  const loanPayments = []
  const netProfit = []
  
  let currentValue = creditAmount
  
  for (let year = 1; year <= 5; year++) {
    // Investment growth
    currentValue = currentValue * (1 + annualGrowthRate)
    const yearlyRevenue = currentValue * 0.3 // 30% of investment value as yearly revenue
    
    investmentGrowth.push({
      year,
      value: Math.round(yearlyRevenue)
    })
    
    // Loan payments
    const yearlyLoanPayment = monthlyPayment * 12
    loanPayments.push({
      year,
      payment: Math.round(yearlyLoanPayment)
    })
    
    // Net profit
    const profit = yearlyRevenue - yearlyLoanPayment
    netProfit.push({
      year,
      profit: Math.round(profit)
    })
  }
  
  projectionData.value = {
    investmentGrowth,
    loanPayments,
    netProfit,
    maxInvestment: Math.max(...investmentGrowth.map(i => i.value)),
    maxLoanPayment: Math.max(...loanPayments.map(l => l.payment)),
    maxNetProfit: Math.max(...netProfit.map(n => Math.abs(n.profit)))
  }
}

const generateInterestRateComparison = () => {
  const creditAmount = params.creditAmount
  const termMonths = 60
  const rates = [6.5, 7.0, 7.5, 8.0, 8.5, 9.0]
  
  interestRateComparison.value = rates.map(rate => {
    const monthlyRate = (rate / 100) / 12
    const monthlyPayment = creditAmount * (monthlyRate * Math.pow(1 + monthlyRate, termMonths)) / 
                          (Math.pow(1 + monthlyRate, termMonths) - 1)
    const totalCost = monthlyPayment * termMonths
    
    return {
      rate,
      monthlyPayment: Math.round(monthlyPayment),
      totalCost: Math.round(totalCost)
    }
  })
}

const generateBreakEvenData = () => {
  const creditAmount = params.creditAmount
  const monthlyRevenue = creditAmount * 0.03 // 3% monthly revenue assumption
  const monthlyExpenses = creditAmount * 0.015 // 1.5% monthly expenses
  const monthlyLoanPayment = 4800 // Approximate monthly payment
  
  const totalMonthlyCost = monthlyExpenses + monthlyLoanPayment
  const requiredMonthlyRevenue = totalMonthlyCost * 1.2 // 20% margin
  const monthsToBreakEven = Math.ceil(creditAmount / (monthlyRevenue - totalMonthlyCost))
  
  breakEvenData.value = {
    months: Math.max(monthsToBreakEven, 1),
    monthlyRevenue: Math.round(requiredMonthlyRevenue),
    totalInvestment: creditAmount
  }
}

const downloadReport = () => {
  window.print()
  // In a real app, you would generate a PDF here
  alert('PDF download functionality would be implemented here')
}

// Generate report on mount
onMounted(() => {
  generateReport()
})
</script>

<style scoped>
@media print {
  .no-print {
    display: none !important;
  }
}

/* Chart animations */
@keyframes growBar {
  from {
    width: 0%;
  }
  to {
    width: var(--target-width);
  }
}

.animate-bar {
  animation: growBar 1.5s ease-out forwards;
}
</style> 