name: Deploy to GitHub Pages

on:
  push:
    branches: [dev-aan-enabling-github-page]  # Using your testing branch
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          echo "NODE_ENV=production" > .env.production
          echo "NUXT_PUBLIC_BASE_URL=/danakito/" >> .env.production
          npm run generate

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .output/public
          branch: gh-pages
          clean: true
          force: true
          token: ${{ secrets.GITHUB_TOKEN }}
